# Generated by Django 5.0.7 on 2024-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('completed', models.BooleanField()),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('picture_repo', models.ImageField(upload_to='taskimage')),
            ],
        ),
    ]
