# Generated by Django 5.0.7 on 2024-07-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='picture_repo',
            field=models.ImageField(blank=True, null=True, upload_to='taskimage'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
