# Generated by Django 5.0.7 on 2024-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doapp', '0003_alter_taskmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
