# Generated by Django 5.0.7 on 2024-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doapp', '0004_alter_taskmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
