# Generated by Django 5.0.7 on 2024-07-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doapp', '0006_remove_taskmodel_picture_repo_taskimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskimage',
            old_name='picture_repo',
            new_name='images',
        ),
    ]
