# Generated by Django 5.0.7 on 2024-07-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doapp', '0007_rename_picture_repo_taskimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_images', to='doapp.taskmodel'),
        ),
    ]
